#!/usr/bin/env python3
"""Sync hermes.config.yaml + .env into HERMES_HOME for native hermes-agent."""

from __future__ import annotations

import os
from pathlib import Path

import yaml
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")


def main() -> None:
    cfg_path = ROOT / "hermes.config.yaml"
    with cfg_path.open(encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh) or {}

    hermes_home = Path(
        os.getenv("HERMES_HOME")
        or cfg.get("hermes_home")
        or (ROOT / ".hermes")
    )
    if not hermes_home.is_absolute():
        hermes_home = ROOT / hermes_home
    hermes_home.mkdir(parents=True, exist_ok=True)

    api_key = os.getenv("HERMES_API_KEY") or ""
    model = str(cfg.get("model") or "hermes-local-mock")
    port = int(cfg.get("port") or 8000)
    host = str(cfg.get("host") or "0.0.0.0")
    upstream = str(
        os.getenv("HERMES_UPSTREAM_BASE_URL")
        or cfg.get("upstream_base_url")
        or "http://127.0.0.1:8001/v1"
    ).rstrip("/")
    upstream_key = os.getenv("HERMES_UPSTREAM_API_KEY") or os.getenv(
        "UPSTREAM_API_KEY", "local-upstream-key"
    )
    log_level = str(cfg.get("log_level") or "info")

    env_text = f"""# Generated by scripts/apply_config.py — do not commit secrets
API_SERVER_ENABLED=true
API_SERVER_KEY={api_key}
API_SERVER_PORT={port}
API_SERVER_HOST={host}
API_SERVER_MODEL_NAME={model}
OPENAI_API_KEY={upstream_key}
OPENAI_BASE_URL={upstream}
HERMES_LOG_LEVEL={log_level}
"""
    (hermes_home / ".env").write_text(env_text, encoding="utf-8")

    config_yaml = f"""# Generated by scripts/apply_config.py
model:
  default: {model}
  provider: custom
  base_url: {upstream}
  api_key: {upstream_key}
agent:
  max_turns: 3
platform_toolsets:
  api_server: []
display:
  personality: ""
logging:
  level: {log_level}
"""
    (hermes_home / "config.yaml").write_text(config_yaml, encoding="utf-8")
    print(f"Synced Hermes home → {hermes_home}")
    print(f"  API server: {host}:{port} model={model}")
    print(f"  Upstream:   {upstream}")


if __name__ == "__main__":
    main()
